apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-vulnerability-scan
  annotations:
    policies.kyverno.io/title: Verify Vulnerability Scan Results
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Verifies that images have been scanned for vulnerabilities and blocks
      deployment if there are more than 1 critical vulnerability without a fix.
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  background: false
  rules:
    - name: check-vulnerability-attestation
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - demo
                - production
      verifyImages:
        - imageReferences:
            - "localhost:5000/*"
            - "*.dkr.ecr.*.amazonaws.com/*"
          attestations:
            - predicateType: https://cosign.sigstore.dev/attestation/vuln/v1
              attestors:
                - entries:
                    - keys:
                        publicKeys: |-
                          -----BEGIN PUBLIC KEY-----
                          # Replace with your cosign.pub content
                          -----END PUBLIC KEY-----
                        rekor:
                          ignoreTlog: true
              conditions:
                - all:
                    # Require the scan was performed
                    - key: "{{ scanner }}"
                      operator: Equals
                      value: "grype"
                    # Block if more than 1 critical without fix
                    - key: "{{ summary.criticalWithoutFix }}"
                      operator: LessThanOrEquals
                      value: "1"
