#!/bin/bash
set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
KEYS_DIR="$PROJECT_DIR/keys"
OUTPUT_FILE="$PROJECT_DIR/policies/kyverno/supply-chain-policy-final.yaml"

echo -e "${YELLOW}Generating Kyverno policy with embedded signing key...${NC}"

# Check if key exists
if [[ ! -f "$KEYS_DIR/cosign.pub" ]]; then
    echo -e "${RED}Error: keys/cosign.pub not found${NC}"
    echo -e "Run ${YELLOW}./scripts/setup.sh${NC} first to generate keys"
    exit 1
fi

# Read the public key and indent it properly for YAML
PUB_KEY=$(cat "$KEYS_DIR/cosign.pub" | sed 's/^/                      /')

cat > "$OUTPUT_FILE" << EOF
# AUTO-GENERATED - Do not edit directly
# Generated by: scripts/generate-policy.sh
# Regenerate with: make policies
#
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: supply-chain-security
  annotations:
    policies.kyverno.io/title: Supply Chain Security Policy
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Blocks container deployments that are:
      1. Not signed with cosign
      2. Not built through an approved pipeline
      3. Have more than 1 critical vulnerability without a fix
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  background: false
  rules:
    - name: verify-image-signature-and-attestations
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - demo
      verifyImages:
        - imageReferences:
            - "localhost:5000/*"
            - "*.dkr.ecr.*.amazonaws.com/*"
          required: true
          mutateDigest: true
          verifyDigest: true
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |-
$PUB_KEY
                    rekor:
                      ignoreTlog: true
                  annotations:
                    pipeline: "demo-build|harness-*"
          attestations:
            - predicateType: https://cosign.sigstore.dev/attestation/vuln/v1
              attestors:
                - entries:
                    - keys:
                        publicKeys: |-
$PUB_KEY
                        rekor:
                          ignoreTlog: true
              conditions:
                - all:
                    - key: "{{ scanner }}"
                      operator: Equals
                      value: "grype"
                    - key: "{{ summary.criticalWithoutFix }}"
                      operator: LessThanOrEquals
                      value: "1"
EOF

echo -e "${GREEN}✓ Generated: policies/kyverno/supply-chain-policy-final.yaml${NC}"
echo ""
echo -e "Apply with: ${YELLOW}kubectl apply -f policies/kyverno/supply-chain-policy-final.yaml${NC}"
